- name: Deploy Web + HTTPS + Firewall
  hosts: web
  become: yes

  vars:
    domain: "quynhdemo.click"
    email: "hieulatao23032001@gmail.com"
    # repo_url: "https://github.com/YOUR-USER/YOUR-REPO.git"
    repo_url: "https://github.com/hieuabcd/webbt2.git"


  tasks:

  # ========================
  # 1. Stop Docker (tránh trùng port 80)
  # ========================
  - name: Stop docker container if exists
    command: docker stop static-web
    ignore_errors: yes

  - name: Remove docker container if exists
    command: docker rm static-web
    ignore_errors: yes

  # ========================
  # 2. Install nginx + certbot + ufw
  # ========================
  - name: Install packages
    apt:
      name:
        - nginx
        - certbot
        - python3-certbot-nginx
        - ufw
        - git
      state: present
      update_cache: yes

  # ========================
  # 3. Pull code từ GitHub
  # ========================
  - name: Remove default web files
    file:
      path: /var/www/html
      state: absent

  - name: Recreate web root
    file:
      path: /var/www/html
      state: directory
  - name: Clone website from GitHub
    git:
      repo: "{{ repo_url }}"
      dest: /var/www/html
      version: main
      force: yes

  # ========================
  # 4. Configure nginx
  # ========================
  - name: Configure nginx site
    copy:
      dest: /etc/nginx/sites-available/default
      content: |
        server {
            listen 80;
            server_name {{ domain }} www.{{ domain }};

            root /var/www/html;
            index index.html;

            location / {
                try_files $uri $uri/ =404;
            }
        }

  - name: Test nginx config
    command: nginx -t

  - name: Reload nginx
    service:
      name: nginx
      state: reloaded

  # ========================
  # 5. Start nginx
  # ========================
  - name: Ensure nginx running
    service:
      name: nginx
      state: started
      enabled: yes

  # ========================
  # 6. Setup Firewall (UFW)
  # ========================
  - name: Allow SSH
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allow Nginx Full
    ufw:
      rule: allow
      name: "Nginx Full"

  - name: Enable UFW
    ufw:
      state: enabled
      policy: deny

  # ========================
  # 7. Generate HTTPS
  # ========================
  - name: Generate SSL certificate
    command: >
      certbot --nginx
      -d {{ domain }}
      -d www.{{ domain }}
      --non-interactive
      --agree-tos
      -m {{ email }}

  # ========================
  # 8. Restart nginx
  # ========================
  - name: Restart nginx
    service:
      name: nginx
      state: restarted