server {
    listen 80;
    server_name quynhdemo.click www.quynhdemo.click;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name quynhdemo.click www.quynhdemo.click;

    ssl_certificate /etc/letsencrypt/live/quynhdemo.click/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/quynhdemo.click/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}