name: Fast Deploy (Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - name: Update code
      run: |
        cd /var/www/html
        git fetch origin main
        git reset --hard origin/main

    - name: Reload Nginx
      run: |
        systemctl reload nginx